export const pageStyles = {
  page: {
    minHeight: "100vh",
    padding: "clamp(16px, 4vw, 32px)",
    background: "linear-gradient(135deg, #0f172a, #020617)",
    color: "#fff",
    fontFamily: "Arial, sans-serif",
  },
  container: {
    maxWidth: "900px",
    margin: "0 auto",
  },
  wideContainer: {
    maxWidth: "1200px",
    margin: "0 auto",
  },
  title: {
    textAlign: "center",
    marginBottom: "clamp(12px, 3vw, 24px)",
    fontSize: "clamp(24px, 6vw, 48px)",
    fontWeight: "800",
    letterSpacing: "-1px",
  },
  nav: {
    display: "flex",
    justifyContent: "center",
    gap: "12px",
    flexWrap: "wrap",
    marginBottom: "clamp(24px, 5vw, 40px)",
  },
  navLink: {
    padding: "10px 20px",
    borderRadius: "8px",
    textDecoration: "none",
    fontWeight: "600",
    fontSize: "14px",
    transition: "background 0.2s",
  },
  navLinkActive: {
    backgroundColor: "#3b82f6",
    color: "#fff",
  },
  navLinkInactive: {
    backgroundColor: "#1e293b",
    color: "#94a3b8",
    border: "1px solid rgba(255,255,255,0.08)",
  },
  section: {
    marginBottom: "clamp(30px, 8vw, 50px)",
    borderBottom: "1px solid rgba(255,255,255,0.05)",
    paddingBottom: "20px",
  },
  sectionTitle: {
    marginBottom: "18px",
    fontSize: "clamp(18px, 4vw, 22px)",
    fontWeight: "700",
  },
  dividerHeader: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
    marginTop: "32px",
    marginBottom: "20px",
    fontSize: "clamp(16px, 3vw, 20px)",
    fontWeight: "700",
    color: "#94a3b8",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  dividerLine: {
    flex: 1,
    height: "1px",
    background: "rgba(255,255,255,0.12)",
  },
  card: {
    backgroundColor: "#1e293b",
    border: "1px solid rgba(255,255,255,0.05)",
    borderRadius: "16px",
    padding: "clamp(16px, 4vw, 24px)",
    marginBottom: "16px",
  },
  input: {
    width: "100%",
    maxWidth: "400px",
    padding: "12px 16px",
    borderRadius: "8px",
    border: "1px solid rgba(255,255,255,0.15)",
    backgroundColor: "#0f172a",
    color: "#fff",
    fontSize: "16px",
    boxSizing: "border-box",
  },
  select: {
    width: "100%",
    maxWidth: "400px",
    padding: "12px 16px",
    borderRadius: "8px",
    border: "1px solid rgba(255,255,255,0.15)",
    backgroundColor: "#0f172a",
    color: "#fff",
    fontSize: "16px",
    boxSizing: "border-box",
    cursor: "pointer",
  },
  button: {
    padding: "12px 28px",
    borderRadius: "8px",
    border: "none",
    backgroundColor: "#3b82f6",
    color: "#fff",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
  },
  buttonDisabled: {
    opacity: 0.5,
    cursor: "not-allowed",
  },
  error: {
    color: "#ef4444",
    marginTop: "8px",
    fontSize: "14px",
  },
  success: {
    color: "#22c55e",
    marginTop: "8px",
    fontSize: "14px",
  },
  toast: {
    position: "fixed",
    bottom: "32px",
    left: "50%",
    transform: "translateX(-50%)",
    zIndex: 1000,
    padding: "14px 24px",
    borderRadius: "10px",
    backgroundColor: "#1e293b",
    border: "1px solid rgba(239, 68, 68, 0.4)",
    color: "#fff",
    fontSize: "15px",
    fontWeight: "600",
    boxShadow: "0 8px 24px rgba(0, 0, 0, 0.4)",
    maxWidth: "min(90vw, 400px)",
    textAlign: "center",
  },
};

export const SCENARIO_SECTIONS = [
  { id: "fire", label: "Fire" },
  { id: "flood", label: "Flood" },
  { id: "earthquake", label: "Earthquake" },
];
